### ISSUE TITLE
Advice: Add expanation about How to use this extension

### ISSUE THREAD

**Issue by MarsTechHAN** [fduman/vscode-nodemcu#1]
Sorry for asking this "kind-of-strange" question...But there is no doucument to show how to use this extension nor any buttons appears...

And Direct use the command Upload NodeMCU ... is malfunction.

**Comment by fduman** [comment]
I agree with you. We definitely need some documentation. I'm working on it.

Could you elaborate more about your "Upload NodeMCU" command's problem on another issue? Which OS are you using etc.

**Comment by MarsTechHAN** [comment]
Running on Windows10, device is at COM7
Error message:

> "No handler found for the command: 'nodemcu.upload'. An extension might be missing an activation event."

BTW, we (as NodeMCU developer group in China) welcome to contribute, so maybe a contribution guide will also be needed

**Comment by fduman** [comment]
Could you open a lua file and then try to execute the upload command please? I haven't tried it on a windows os yet. I hope it will execute the command properly.

**Comment by MarsTechHAN** [comment]
![image](https://cloud.githubusercontent.com/assets/10462805/16707237/e5f82bd8-45f9-11e6-9499-5004ef1ad06c.png)
![image](https://cloud.githubusercontent.com/assets/10462805/16707239/ed8e3658-45f9-11e6-8521-670fb9e9efc2.png)

**Comment by delfinof** [comment]
Same happens to me

**Comment by fduman** [comment]
I fixed the problem for Windows OS only. But now extension can't run on OS X and Linux. I try to find a solution.

Could you try the extension on Windows please?

**Comment by fduman** [comment]
I have started to write some documentation in Wiki. This issue was mainly a documentation question. So I closed this. If you catch some problems with the extension, please open a different issue.
